CREATE OR REPLACE FORCE EDITIONABLE VIEW "V_VFW_KFZ" ("ID_KFZ", "ID_FAKTURA", "ID_HAENDLER_ALS_FAKTURA", "ID_HAENDLER_ALS_AKTUELL", "ID_HAENDLER_ALS_ZULASSUNG", "KOMMISSION_NUMMER", "KOMMISSION_NUMMER_JAHR", "FGN", "HAT_SPORTLICHES_KIT", "MODELL_JAHR", "CARLINE_NAME", "CARLINE_CODE", "MODELL_AUSSTATTUNG_NAME", "MODELL_CODE", "DATUM_BESTELLUNG_NADIN", "KUNDE_KATEGORIE", "DATUM_SCHAUGLASWOCHE", "PRODUKTIONSWOCHE", "AKTION_IMPORTEUR_01", "AKTION_IMPORTEUR_02", "AKTION_IMPORTEUR_03", "DATUM_FAKTURA", "RECH_TYP", "DATUM_ZULASSUNG", "VFW_ABMELDUNG_DATUM", "VFW_ENDE_DATUM", "VFW_UMMELDUNG_DATUM", "VFW_KD_VERTRAG_DATUM", "DATUM_PRODUKTION", "KFZ_KENNZEICHEN", "DATUM_KUNDE_VERTRAG", "DATUM_ABRUF", "DATUM_UMFUHR", "UPE_KORRIGIERT", "DATUM_STORNO", "IST_GELOESCHT_STORNIERT_KONSOLIDIERT", "MOTOR_KRAFTSTOFFART", "DATUM_KUNDE_ZUWEISUNG", "MARKE", "VFW_ANFANG_DATUM") AS 
  SELECT
    kfz./*F*/ID_KFZ/*/F*/,
    fkt./*F*/ID_FAKTURA/*/F*/,
    fkt.ID_HAENDLER /*F*/ID_HAENDLER_ALS_FAKTURA/*/F*/,
    bst./*F*/ID_HAENDLER_ALS_AKTUELL/*/F*/,   
    zls.ID_HAENDLER /*F*/ID_HAENDLER_ALS_ZULASSUNG/*/F*/,
    kfz./*F*/KOMMISSION_NUMMER/*/F*/,
    kfz./*F*/KOMMISSION_NUMMER_JAHR/*/F*/,
    kfz./*F*/FGN/*/F*/,
    kfz./*F*/HAT_SPORTLICHES_KIT/*/F*/,  
    kfz./*F*/MODELL_JAHR/*/F*/,
    cln.NAME /*F*/CARLINE_NAME/*/F*/,
    cln.CODE /*F*/CARLINE_CODE/*/F*/,
    kfz.MODELL_AUSSTATTUNG_CODE /*F*/MODELL_AUSSTATTUNG_NAME/*/F*/,
    mo.CODE /*F*/MODELL_CODE/*/F*/,    
    bst./*F*/DATUM_BESTELLUNG_NADIN/*/F*/,
    bst./*F*/KUNDE_KATEGORIE/*/F*/,
    bst./*F*/DATUM_SCHAUGLASWOCHE/*/F*/,
    bst./*F*/PRODUKTIONSWOCHE/*/F*/,
    bst./*F*/AKTION_IMPORTEUR_01/*/F*/,
    bst./*F*/AKTION_IMPORTEUR_02/*/F*/,
    bst./*F*/AKTION_IMPORTEUR_03/*/F*/,
    fkt.DATUM /*F*/DATUM_FAKTURA/*/F*/,
    fkt./*F*/RECH_TYP/*/F*/,
    zls./*F*/DATUM_ZULASSUNG/*/F*/,
    zls./*F*/VFW_ABMELDUNG_DATUM/*/F*/,
    zls./*F*/VFW_ENDE_DATUM/*/F*/,
    zls./*F*/VFW_UMMELDUNG_DATUM/*/F*/,
    zls./*F*/VFW_KD_VERTRAG_DATUM/*/F*/,
    bst./*F*/DATUM_PRODUKTION/*/F*/,
    zls./*F*/KFZ_KENNZEICHEN/*/F*/,   
    bst./*F*/DATUM_KUNDE_VERTRAG/*/F*/,
    bst./*F*/DATUM_ABRUF/*/F*/,
    bst./*F*/DATUM_UMFUHR/*/F*/,
    fkt./*F*/UPE_KORRIGIERT/*/F*/,
    bst./*F*/DATUM_STORNO/*/F*/,
    kfz./*F*/IST_GELOESCHT_STORNIERT_KONSOLIDIERT/*/F*/,
    kfz./*F*/MOTOR_KRAFTSTOFFART/*/F*/,
    bst./*F*/DATUM_KUNDE_ZUWEISUNG/*/F*/,
    kfz./*F*/MARKE/*/F*/,    
    zls./*F*/VFW_ANFANG_DATUM/*/F*/
FROM
    KFZ kfz
JOIN
    BESTELLUNG bst ON kfz.ID_KFZ = bst.ID_KFZ
LEFT JOIN
    FAKTURA fkt ON kfz.ID_KFZ = fkt.ID_KFZ
LEFT JOIN
    ZULASSUNG zls ON kfz.ID_KFZ = zls.ID_KFZ 
JOIN
    MODELL mo ON kfz.ID_MODELL = mo.ID_MODELL
JOIN
    CARLINE CLN ON MO.ID_CARLINE = CLN.ID_CARLINE;
    
   
   SELECT * FROM VKF_SEAT_DE_FEATURE_UTEST.V_VFW_KFZ WHERE ROWNUM = 1;